--Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES 

--Explore all the cloumns in the tables
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

--Explore all the countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers

--Explore all products ategories"The Major Divisions"
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
ORDER BY 1,2,3

--Date exploration
--Find the date of the first and last order
--How many years of sales are avaiable

SELECT 
MIN(order_date) first_order_date, 
MAX(order_date) last_order_date,
DATEDIFF(year,MIN(order_date),MAX(Order_date)) As order_range_years,
DATEDIFF(month,MIN(order_date),MAX(Order_date)) As order_range_months
FROM gold.fact_sales;

--Find the youngest and the oldest Customers
SELECT 
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE()) as oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year,MAX(birthdate),GETDATE()) as youngest_age
FROM GOLD.dim_customers
--Measure Exploration

--Find the total Sales
SELECT 
SUM(sales_amount) AS Total_sales
FROM gold.fact_sales

--Find how many tiems are sold
SELECT 
SUM(quantity) AS Total_quantity
FROM gold.fact_sales

--Find the average selling price
SELECT 
AVG(price) AS Avg_selling_Price
FROM gold.fact_sales

--Find the Total number of Orders
SELECT 
Count(order_number) AS Total_oredrs
FROM gold.fact_sales;
SELECT 
Count(DISTINCT(order_number)) AS Total_oredrs
FROM gold.fact_sales;

--Find the Total number of Products
SELECT
COUNT(product_key) AS Total_products
FROM gold.dim_products;

SELECT
COUNT(DISTINCT(product_key)) AS Total_products
FROM gold.dim_products;

--Find the Total number of Customers
SELECT 
COUNT(customer_key) AS Total_customers
FROM gold.dim_customers;
SELECT 
COUNT(DISTINCT(customer_key)) AS Total_customers
FROM gold.dim_customers;

--Find the Total number of Customers that has places an order
SELECT 
COUNT(DISTINCT(customer_key)) AS Total_customers
FROM gold.fact_sales;
--Genetrate a Report that shows all the key metrics of the business
SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr.Orders' ,COUNT(DISTINCT(order_number)) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products',COUNT(DISTINCT(product_key)) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(DISTINCT(customer_key)) FROM gold.dim_customers

--Magintude Analysis
--Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country 
ORDER BY total_customers DESC

--Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category
SELECT
category,
COUNT(product_key) AS Tolat_products
FROM gold.dim_products
GROUP BY category
ORDER BY  Tolat_products DESC

--What is average costs in each category?
SELECT
category,
AVG(cost) AS Avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC

--What is the total revenue genrated for each category?
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key =f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Find total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key =f.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries?
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key =f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

--Ranking Analysis
--Which 5 products generated the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) As total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY product_name 
ORDER BY total_revenue DESC

--What are the 5 Worst-performing products in the terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) As total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY product_name 
ORDER BY total_revenue

--Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key =f.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

--3 customers with fewest orders placed
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT(order_number)) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key =f.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders
